# Generated by Django 4.1.8 on 2024-04-17 14:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0005_blogtagindexpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название фильма на русском"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "country",
                    models.CharField(
                        max_length=255, verbose_name="Страна производитель"
                    ),
                ),
                ("genre", models.CharField(max_length=255, verbose_name="Жанр")),
                (
                    "poster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Films",
            },
        ),
        migrations.AddField(
            model_name="blogpage",
            name="film",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.film"
            ),
        ),
    ]
