# Generated by Django 4.1.8 on 2024-04-17 16:51

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0006_film_blogpage_film"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="film",
            options={"verbose_name": "фильм", "verbose_name_plural": "фильмы"},
        ),
        migrations.AddField(
            model_name="film",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Год выхода фильма"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="film",
            field=modelcluster.fields.ParentalManyToManyField(to="blog.film"),
        ),
        migrations.AlterField(
            model_name="film",
            name="country",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Страна производитель",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Постер",
            ),
        ),
    ]
