# Generated by Django 4.1.8 on 2024-04-17 17:14

import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("blog", "0007_alter_film_options_film_year_alter_blogpage_film_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="genre",
        ),
        migrations.AddField(
            model_name="film",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPageTag",
                to="taggit.Tag",
                verbose_name="Теги для фильма",
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Основной текст"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="film",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.film", verbose_name="Фильм"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPageTag",
                to="taggit.Tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="blogpagegalleryimage",
            name="caption",
            field=models.CharField(blank=True, max_length=250, verbose_name="Описание"),
        ),
    ]
