# Generated by Django 4.1.8 on 2024-04-17 17:27

import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("blog", "0008_remove_film_genre_film_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
            ],
            options={
                "verbose_name": "страна",
                "verbose_name_plural": "страны",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
            },
        ),
        migrations.RemoveField(
            model_name="film",
            name="tags",
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPageTag",
                to="taggit.Tag",
                verbose_name="Теги для блога",
            ),
        ),
        migrations.RemoveField(
            model_name="film",
            name="country",
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(to="blog.genre", verbose_name="Жанр"),
        ),
        migrations.AddField(
            model_name="film",
            name="country",
            field=models.ManyToManyField(
                to="blog.country", verbose_name="Страна-производитель"
            ),
        ),
    ]
