# Generated by Django 4.1.8 on 2024-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_blogpage_options_alter_blogpage_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="film",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="films",
            field=models.ManyToManyField(blank=True, to="blog.film"),
        ),
    ]
