# Generated by Django 4.2.10 on 2024-04-18 15:23

import django.db.models.deletion
import modelcluster.fields
import sorl.thumbnail.fields
from django.db import migrations, models

import kino.utils.other.generate_hide_url
import kino.utils.other.thumbnail


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0024_alter_country_name_alter_film_trailer_and_more"),
        ("blog", "0012_remove_blogpage_films_blogpage_film"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название на русском"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "avg_rating",
                    models.FloatField(
                        blank=True, default=0.0, verbose_name="Рейтинг пользователей"
                    ),
                ),
                (
                    "age_restriction",
                    models.CharField(
                        choices=[
                            ("0+", "0+"),
                            ("6+", "6+"),
                            ("12+", "12+"),
                            ("16+", "16+"),
                            ("18+", "18+"),
                        ],
                        default="0+",
                        verbose_name="Возрастное ограничение",
                    ),
                ),
                (
                    "trailer",
                    models.URLField(blank=True, default=None, verbose_name="Трейлер"),
                ),
                (
                    "poster",
                    sorl.thumbnail.fields.ImageField(
                        blank=True,
                        upload_to=kino.utils.other.generate_hide_url.upload_to_posters,
                        validators=[kino.utils.other.thumbnail.clean_poster],
                        verbose_name="Постер",
                    ),
                ),
                (
                    "country",
                    modelcluster.fields.ParentalManyToManyField(
                        to="cards.country", verbose_name="Страна производитель"
                    ),
                ),
                (
                    "genre",
                    modelcluster.fields.ParentalManyToManyField(
                        to="cards.genre", verbose_name="Жанр"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="film",
            name="country",
        ),
        migrations.RemoveField(
            model_name="film",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="film",
            name="poster",
        ),
        migrations.CreateModel(
            name="FilmDefaultBlog",
            fields=[
                (
                    "cardblog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.cardblog",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, verbose_name="Год выхода фильма"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("blog.cardblog",),
        ),
        migrations.CreateModel(
            name="SerialDefaultBlog",
            fields=[
                (
                    "cardblog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.cardblog",
                    ),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True, verbose_name="Год начала выхода сериала"
                    ),
                ),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=2024,
                        verbose_name="Год окончания выхода сериала",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("blog.cardblog",),
        ),
    ]
