# Generated by Django 4.2.10 on 2024-04-18 15:32

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0024_alter_country_name_alter_film_trailer_and_more"),
        ("blog", "0013_cardblog_remove_film_country_remove_film_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardblog",
            name="country",
            field=modelcluster.fields.ParentalManyToManyField(
                to="cards.country", verbose_name="Страна производитель"
            ),
        ),
        migrations.AlterField(
            model_name="cardblog",
            name="genre",
            field=modelcluster.fields.ParentalManyToManyField(
                to="cards.genre", verbose_name="Жанр"
            ),
        ),
    ]
