# Generated by Django 4.2.10 on 2024-04-18 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_cardblog_country_alter_cardblog_genre"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Film",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
