# Generated by Django 4.2.10 on 2024-04-22 15:00

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations, models

import kino.blog.snippets


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0024_alter_country_name_alter_film_trailer_and_more"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0015_delete_country_delete_film_delete_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("profession", models.CharField(max_length=255)),
                (
                    "author_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
            },
        ),
        migrations.RemoveField(
            model_name="cardblog",
            name="country",
        ),
        migrations.RemoveField(
            model_name="cardblog",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="filmblog",
            name="cardblog_ptr",
        ),
        migrations.RemoveField(
            model_name="serialblog",
            name="cardblog_ptr",
        ),
        migrations.CreateModel(
            name="PhotoFilmBlog",
            fields=[],
            options={
                "verbose_name": "Кадр из фильма",
                "verbose_name_plural": "Кадры из фильмов",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cards.photofilm",),
        ),
        migrations.CreateModel(
            name="PhotoSerialBlog",
            fields=[],
            options={
                "verbose_name": "Кадр из сериала",
                "verbose_name_plural": "Кадры из сериалов",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cards.photoserial",),
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="film",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="serial",
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.RichTextBlock(label="Текст блога")),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            help_text="Добавьте изображение", label="Изображение"
                        ),
                    ),
                    (
                        "film",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.FilmBlog,
                            help_text="Укажите фильм",
                            label="Фильм",
                            required=False,
                        ),
                    ),
                    (
                        "serial",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.SerialBlog,
                            help_text="Укажите сериал",
                            label="Сериал",
                            required=False,
                        ),
                    ),
                    (
                        "photo_film",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.PhotoFilmBlog,
                            help_text="Укажите кадр из фильма",
                            label="Кадр из фильма",
                        ),
                    ),
                    (
                        "photo_serial",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.PhotoSerialBlog,
                            help_text="Укажите кадр из сериала",
                            label="Кадр из сериала",
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Основная часть",
            ),
        ),
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
        migrations.DeleteModel(
            name="CardBlog",
        ),
        migrations.DeleteModel(
            name="FilmBlog",
        ),
        migrations.DeleteModel(
            name="SerialBlog",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="authors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.author"
            ),
        ),
        migrations.CreateModel(
            name="FilmBlog",
            fields=[],
            options={
                "verbose_name": "фильм",
                "verbose_name_plural": "фильмы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cards.film",),
        ),
        migrations.CreateModel(
            name="SerialBlog",
            fields=[],
            options={
                "verbose_name": "сериал",
                "verbose_name_plural": "сериалы",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cards.serial",),
        ),
    ]
