# Generated by Django 4.2.10 on 2024-04-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cards", "0025_alter_film_film_crew_alter_serial_film_crew"),
        ("blog", "0016_author_remove_cardblog_country_remove_cardblog_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.country",
                verbose_name="Страна",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="author_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Фотография автора",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="profession",
            field=models.CharField(max_length=255, verbose_name="Профессия"),
        ),
    ]
