# Generated by Django 4.2.10 on 2024-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_alter_author_country_alter_author_profession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="work_experience",
            field=models.PositiveSmallIntegerField(blank=True, verbose_name="Стаж"),
        ),
    ]
