# Generated by Django 4.2.10 on 2024-04-24 12:05

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations

import kino.blog.snippets


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_alter_author_profession"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmFullBlog",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("blog.filmblog",),
        ),
        migrations.CreateModel(
            name="FilmShortBlog",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("blog.filmblog",),
        ),
        migrations.CreateModel(
            name="SerialFullBlog",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("blog.serialblog",),
        ),
        migrations.CreateModel(
            name="SerialShortBlog",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("blog.serialblog",),
        ),
        migrations.RemoveField(
            model_name="author",
            name="work_experience",
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.RichTextBlock(label="Текст блога")),
                    (
                        "image",
                        wagtail.images.blocks.ImageChooserBlock(
                            help_text="Добавьте изображение", label="Изображение"
                        ),
                    ),
                    (
                        "film",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.FilmBlog,
                            help_text="Укажите фильм с описанием и трейлером",
                            label="Фильм",
                            required=False,
                        ),
                    ),
                    (
                        "film_short",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.FilmShortBlog,
                            help_text="Укажите фильм с краткой информацией",
                            label="Фильм(кратко)",
                            required=False,
                        ),
                    ),
                    (
                        "film_full",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.FilmFullBlog,
                            help_text="Укажите фильм с кадрами",
                            label="Фильм(с кадрами)",
                            required=False,
                        ),
                    ),
                    (
                        "serial",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.SerialBlog,
                            help_text="Укажите сериал",
                            label="Сериал",
                            required=False,
                        ),
                    ),
                    (
                        "photo_film",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.PhotoFilmBlog,
                            help_text="Укажите кадр из фильма",
                            label="Кадр из фильма",
                        ),
                    ),
                    (
                        "photo_serial",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            kino.blog.snippets.PhotoSerialBlog,
                            help_text="Укажите кадр из сериала",
                            label="Кадр из сериала",
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Основная часть",
            ),
        ),
    ]
