image: docker:20.10.16
stages:
  - lint
  - test
  - deploy

variables:
  POSTGRES_USER: 'kino'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_kino'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

precommit:
  stage: lint
  image: python:3.11
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install -q pre-commit
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files

pytest:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker-compose -f test.yml build
    - docker-compose -f test.yml run --rm django_kino_test python manage.py migrate
    - docker-compose -f test.yml up -d
  script:
    - docker-compose -f test.yml run --rm django_kino_test python manage.py makemigrations --check --dry-run
    - docker-compose -f test.yml run --rm django_kino_test mypy .
    - docker-compose -f test.yml run django_kino_test pytest -n auto --create-db
    - docker-compose -f test.yml down
    - docker image rm postgres_kino_test

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/id_rsa.pub
    - ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa -tt $SERVER_USER@$SERVER_HOST << EOF
      cd kino_server/Belotserkovskiy
      git pull https://${CI_USERNAME}:${CI_PASSWORD}@${CI_PATH}
      docker-compose -f production.yml up --build --detach
      docker image prune -f || true
      EOF
  when: manual
