version: '3'

volumes:
  kino_local_postgres_data: {}
  kino_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: kino_local_django
    container_name: kino_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    working_dir: /app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '7362:7362'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kino_production_postgres
    container_name: kino_local_postgres
    volumes:
      - kino_local_postgres_data:/var/lib/postgresql/data
      - kino_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: kino_local_docs
    container_name: kino_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./kino:/app/kino:z
    ports:
      - '9090:9090'
    command: /start-docs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: kino_local_mailpit
    ports:
      - "8026:8025"

  redis:
    image: docker.io/redis:6
    container_name: kino_local_redis

  celeryworker:
    <<: *django
    image: kino_local_celeryworker
    container_name: kino_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: kino_local_celerybeat
    container_name: kino_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: kino_local_flower
    container_name: kino_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
