version: '3'

volumes:
  postgres_kino_local_data: {}
  postgres_kino_local_data_backups: {}

services:
  django_kino_local: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_kino_local
    container_name: django_kino_local
    depends_on:
      - postgres_kino_local
      - redis_kino_local
      - mailpit_kino_local
    volumes:
      - /app
    working_dir: /app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres_kino_local:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres_kino_local
    container_name: postgres_kino_local
    volumes:
      - postgres_kino_local_data:/var/lib/postgresql/data
      - postgres_kino_local_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs_kino_local:
    image: docs_kino_local
    container_name: docs_kino_local
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./kino:/app/kino:z
    ports:
      - '9090:9090'
    command: /start-docs

  mailpit_kino_local:
    image: docker.io/axllent/mailpit:latest
    container_name: mailpit_kino_local
    ports:
      - "8026:8025"

  redis_kino_local:
    image: docker.io/redis:6
    container_name: redis_kino_local

  celeryworker_kino_local:
    <<: *django
    image: celeryworker_kino_local
    container_name: celeryworker_kino_local
    depends_on:
      - redis_kino_local
      - postgres_kino_local
      - mailpit_kino_local
    ports: []
    command: /start-celeryworker

  celerybeat_kino_local:
    <<: *django
    image: celerybeat_kino_local
    container_name: celerybeat_kino_local
    depends_on:
      - redis_kino_local
      - postgres_kino_local
      - mailpit_kino_local
    ports: []
    command: /start-celerybeat

  flower_kino_local:
    <<: *django
    image: flower_kino_local
    container_name: flower_kino_local
    ports:
      - '5555:5555'
    command: /start-flower
