version: '3.9'

services:
  django_kino_test:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_kino_test
    container_name: django_kino_test
    depends_on:
      - postgres_kino_test
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    command: /start

  postgres_kino_test:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres_kino_test
    container_name: postgres_kino_test
    env_file:
      - ./.envs/.test/.postgres
