# Generated by Django 4.2.10 on 2024-02-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_film_age_restriction_alter_film_id_imdb_and_more'),
        ('filmcrew', '0002_alter_photoperson_options_remove_filmcrew_films_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcrew',
            name='birthplace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.country', verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='filmcrew',
            name='profession',
            field=models.CharField(choices=[('director', 'Режиссёр'), ('actor', 'Актёр'), ('cinematographer', 'Оператор (камера)'), ('editor', 'Монтажёр'), ('screenwriter', 'Сценарист'), ('designer', 'Художник-постановщик'), ('sound_engineer', 'Звукоинженер (звукорежиссёр)'), ('composer', 'Композитор'), ('producer', 'Продюсер')], verbose_name='Профессия'),
        ),
    ]
