# Generated by Django 4.2.10 on 2024-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmcrew', '0003_alter_filmcrew_birthplace_alter_filmcrew_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcrew',
            name='birthplace',
            field=models.CharField(max_length=155, verbose_name='Место рождения'),
        ),
    ]
