# Generated by Django 4.2.10 on 2024-02-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_film_age_restriction_alter_film_id_imdb_and_more'),
        ('filmcrew', '0004_alter_filmcrew_birthplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcrew',
            name='birthplace',
        ),
        migrations.AddField(
            model_name='filmcrew',
            name='country',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.country', verbose_name='Место рождения'),
            preserve_default=False,
        ),
    ]
