# Generated by Django 4.2.10 on 2024-03-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmcrew', '0006_alter_filmcrew_options_alter_photoperson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmcrew',
            options={'verbose_name': 'участник производства', 'verbose_name_plural': 'участники производства'},
        ),
        migrations.AlterModelOptions(
            name='photoperson',
            options={'verbose_name': 'фотография участника', 'verbose_name_plural': 'фотографии участников'},
        ),
    ]
