# Generated by Django 4.2.10 on 2024-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmcrew', '0007_alter_filmcrew_options_alter_photoperson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmcrew',
            name='profession',
            field=models.CharField(choices=[('Режиссёр', 'Режиссёр'), ('Актёр', 'Актёр'), ('Оператор', 'Оператор'), ('Монтажёр', 'Монтажёр'), ('Сценарист', 'Сценарист'), ('Художник-постановщик', 'Художник-постановщик'), ('Звукорежиссёр', 'Звукорежиссёр'), ('Композитор', 'Композитор'), ('Продюсер', 'Продюсер')], verbose_name='Профессия'),
        ),
    ]
