# Generated by Django 4.2.10 on 2024-02-22 11:24

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import kino.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objects_id', models.PositiveIntegerField()),
                ('season', models.PositiveSmallIntegerField(default=None, verbose_name='Номер сезона')),
                ('episode', models.PositiveSmallIntegerField(default=None, verbose_name='Номер серии')),
                ('source_link', models.URLField(verbose_name='Ссылка на исходное видео в S3')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', enumchoicefield.fields.EnumChoiceField(enum_class=kino.enums.QualityChoose, max_length=7, verbose_name='Качество')),
                ('video_url', models.URLField(default=None, verbose_name='Ссылка на медиа')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки качества')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.media', verbose_name='Медиа')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', enumchoicefield.fields.EnumChoiceField(default='waiting', enum_class=kino.enums.StatusChoose, max_length=10, verbose_name='Статус выполнения задачи')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки задачи')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.media', verbose_name='Медиа')),
            ],
        ),
    ]
