# Generated by Django 4.2.10 on 2024-02-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('processing', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Произошла ошибка')], default='waiting', verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='quality',
            field=models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], verbose_name='Качество'),
        ),
    ]
