# Generated by Django 4.2.10 on 2024-02-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_task_status_alter_videoquality_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='objects_id',
            new_name='object_id',
        ),
    ]
