# Generated by Django 4.2.10 on 2024-02-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_objects_id_media_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медифайлы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Загрузка медиафайла', 'verbose_name_plural': 'Загрузки медиафайлов'},
        ),
        migrations.AlterModelOptions(
            name='videoquality',
            options={'verbose_name': 'Качество медиафайла', 'verbose_name_plural': 'Качества медиафайла'},
        ),
    ]
