# Generated by Django 4.2.10 on 2024-02-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_media_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='episode',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='media',
            name='season',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Номер сезона'),
        ),
    ]
