# Generated by Django 4.2.10 on 2024-02-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_media_episode_alter_media_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='source_link',
            field=models.CharField(verbose_name='Ссылка на исходное видео в S3 ИЛИ путь к файлу на компьютере'),
        ),
    ]
