# Generated by Django 4.2.10 on 2024-02-29 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0006_alter_media_source_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Статус загрузки', 'verbose_name_plural': 'Статусы загрузок'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('processing', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Произошла ошибка')], verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='quality',
            field=models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], verbose_name='Качество'),
        ),
        migrations.CreateModel(
            name='HistoricalMedia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('season', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Номер сезона')),
                ('episode', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Номер серии')),
                ('source_link', models.CharField(verbose_name='Ссылка на исходное видео в S3 ИЛИ путь к файлу на компьютере')),
                ('date_added', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Медиафайл',
                'verbose_name_plural': 'historical Медифайлы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
