# Generated by Django 4.2.10 on 2024-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_task_options_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmedia',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical медиафайл', 'verbose_name_plural': 'historical медифайлы'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'медиафайл', 'verbose_name_plural': 'медифайлы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'статус загрузки', 'verbose_name_plural': 'статусы загрузок'},
        ),
        migrations.AlterModelOptions(
            name='videoquality',
            options={'verbose_name': 'качество медиафайла', 'verbose_name_plural': 'качества медиафайла'},
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='video_url',
            field=models.CharField(default=None, verbose_name='Ссылка на медиа'),
        ),
    ]
