# Generated by Django 4.2.10 on 2024-03-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_historicalmedia_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoquality',
            name='encrypted_url',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Зашифрованная ссылка на медиа'),
        ),
        migrations.AlterField(
            model_name='videoquality',
            name='video_url',
            field=models.CharField(default=None, verbose_name='Оригинальная ссылка на медиа'),
        ),
    ]
