# Generated by Django 4.2.10 on 2024-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_videoquality_encrypted_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoquality',
            name='encrypted_url',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Зашифрованная ссылка на медиа'),
        ),
    ]
