# Generated by Django 4.2.10 on 2024-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_historicalmedia_options_alter_media_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='video.media', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='user',
            name='see_later',
            field=models.ManyToManyField(blank=True, related_name='see_later_users', to='video.media', verbose_name='Просмотреть позже'),
        ),
        migrations.AddField(
            model_name='user',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched_users', to='video.media', verbose_name='Просмотрено'),
        ),
    ]
