# Generated by Django 4.2.10 on 2024-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_remove_user_favorite_remove_user_see_later_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
