# Generated by Django 4.2.10 on 2024-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_rates_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='value',
            field=models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')], verbose_name='Оценка'),
        ),
    ]
