# Generated by Django 4.2.10 on 2024-03-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_rates_date_created_alter_rates_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
    ]
