# Generated by Django 4.2.10 on 2024-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='photofilm',
            options={'verbose_name': 'Фото фильмов'},
        ),
        migrations.AlterField(
            model_name='film',
            name='rating_imdb',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='rating_imdb',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Рейтинг IMDb'),
        ),
    ]
