# Generated by Django 4.2.10 on 2024-02-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_country_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(choices=[('zero', '0+'), ('six', '6+'), ('twelve', '12+'), ('sixteen', '16+'), ('eighteen', '18+')], default='0+', verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='id_imdb',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID фильма/сериала на IMDb'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='age_restriction',
            field=models.CharField(choices=[('zero', '0+'), ('six', '6+'), ('twelve', '12+'), ('sixteen', '16+'), ('eighteen', '18+')], default='0+', verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='id_imdb',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID фильма/сериала на IMDb'),
        ),
    ]
