# Generated by Django 4.2.10 on 2024-02-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_film_age_restriction_alter_film_id_imdb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='avg_rating',
        ),
    ]
