# Generated by Django 4.2.10 on 2024-02-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_film_avg_rating_remove_serial_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Рейтинг пользователей'),
        ),
        migrations.AddField(
            model_name='serial',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Рейтинг пользователей'),
        ),
    ]
