# Generated by Django 4.2.10 on 2024-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='photofilm',
            options={'verbose_name': 'фотография фильма', 'verbose_name_plural': 'фотографии фильмов'},
        ),
        migrations.AlterModelOptions(
            name='photoserial',
            options={'verbose_name': 'фотография сериала', 'verbose_name_plural': 'фотографии сериалов'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'сериал', 'verbose_name_plural': 'сериалы'},
        ),
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('0', '0+'), ('6', '6+'), ('12', '12+'), ('16', '16+'), ('18', '18+')], default=0, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, default=None, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Год выхода фильма'),
        ),
        migrations.AlterField(
            model_name='photofilm',
            name='photo_film',
            field=models.ImageField(blank=True, upload_to='photos_films/', verbose_name='Кадры из фильма'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('0', '0+'), ('6', '6+'), ('12', '12+'), ('16', '16+'), ('18', '18+')], default=0, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2024, verbose_name='Год окончания выхода сериала'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='num_episodes',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество серий'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='num_seasons',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество сезонов'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Год начала выхода сериала'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='trailer',
            field=models.URLField(blank=True, default=None, verbose_name='Трейлер'),
        ),
    ]
