# Generated by Django 4.2.10 on 2024-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_historicalmedia_options_alter_media_options_and_more'),
        ('cards', '0010_alter_photofilm_photo_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='quality',
            field=models.ManyToManyField(to='video.videoquality', verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='serial',
            name='quality',
            field=models.ManyToManyField(to='video.videoquality', verbose_name='Качество'),
        ),
    ]
