# Generated by Django 4.2.10 on 2024-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comments_options_alter_rates_options'),
        ('cards', '0011_film_quality_serial_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.ManyToManyField(to='comments.comment', verbose_name='Коментарии'),
        ),
        migrations.AddField(
            model_name='serial',
            name='comments',
            field=models.ManyToManyField(to='comments.comment', verbose_name='Коментарии'),
        ),
    ]
