# Generated by Django 4.2.10 on 2024-03-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_film_comments_serial_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='film',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='quality',
        ),
        migrations.AddField(
            model_name='film',
            name='quality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='serial',
            name='quality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Качество'),
        ),
    ]
