# Generated by Django 4.2.10 on 2024-03-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_remove_film_comments_remove_serial_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='quality',
        ),
    ]
