# Generated by Django 4.2.10 on 2024-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_film_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='media',
        ),
        migrations.AlterField(
            model_name='photoserial',
            name='photo_serial',
            field=models.ImageField(blank=True, null=True, upload_to='photos_serials/', verbose_name='Кадры из фильма'),
        ),
    ]
