# Generated by Django 4.2.10 on 2024-03-20 18:24

from django.db import migrations, models
import kino.utils.other.generate_hide_url


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_remove_film_media_alter_photoserial_photo_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to=kino.utils.other.generate_hide_url.upload_to_posters, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='photofilm',
            name='photo_film',
            field=models.ImageField(blank=True, null=True, upload_to=kino.utils.other.generate_hide_url.upload_to_films, verbose_name='Кадры из фильма'),
        ),
        migrations.AlterField(
            model_name='photoserial',
            name='photo_serial',
            field=models.ImageField(blank=True, null=True, upload_to=kino.utils.other.generate_hide_url.upload_to_serials, verbose_name='Кадры из фильма'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=models.ImageField(blank=True, upload_to=kino.utils.other.generate_hide_url.upload_to_posters, verbose_name='Постер'),
        ),
    ]
