# Generated by Django 4.2.10 on 2024-03-25 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_alter_film_poster_alter_photofilm_photo_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 14, 31, 24, 879376), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='photofilm',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 14, 31, 24, 903311), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='photoserial',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 14, 31, 24, 905370), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='serial',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 14, 31, 24, 879376), verbose_name='Дата создания'),
        ),
    ]
