# Generated by Django 4.2.10 on 2024-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_film_date_created_photofilm_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photofilm',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photoserial',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
