# Generated by Django 4.2.10 on 2024-03-27 19:30

from django.db import migrations
import kino.utils.other.generate_hide_url
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_alter_photofilm_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=kino.utils.other.generate_hide_url.upload_to_posters, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=kino.utils.other.generate_hide_url.upload_to_posters, verbose_name='Постер'),
        ),
    ]
