# Generated by Django 4.2.10 on 2024-04-05 11:11

from django.db import migrations, models
import kino.utils.other.generate_hide_url
import kino.utils.other.thumbnail
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_alter_film_poster_alter_serial_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='0+', verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=kino.utils.other.generate_hide_url.upload_to_posters, validators=[kino.utils.other.thumbnail.clean_poster], verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='age_restriction',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='0+', verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=kino.utils.other.generate_hide_url.upload_to_posters, validators=[kino.utils.other.thumbnail.clean_poster], verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='trailer',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Трейлер'),
        ),
    ]
