# Generated by Django 4.2.10 on 2024-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_alter_film_age_restriction_alter_film_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, default=None, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='trailer',
            field=models.URLField(blank=True, default=None, verbose_name='Трейлер'),
        ),
    ]
