# Generated by Django 4.2.10 on 2024-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmcrew", "0008_alter_filmcrew_profession"),
        ("cards", "0024_alter_country_name_alter_film_trailer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="film_crew",
            field=models.ManyToManyField(
                blank=True, to="filmcrew.filmcrew", verbose_name="Съемочная группа"
            ),
        ),
        migrations.AlterField(
            model_name="serial",
            name="film_crew",
            field=models.ManyToManyField(
                blank=True, to="filmcrew.filmcrew", verbose_name="Съемочная группа"
            ),
        ),
    ]
