name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install pre-commit
      - name: Run pre-commit
        env:
          PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: kino
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: test_kino
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U kino"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and start containers
        run: |
          docker-compose -f test.yml build
          docker-compose -f test.yml run --rm django_kino_test python manage.py migrate
          docker-compose -f test.yml up -d
      - name: Run tests
        run: |
          docker-compose -f test.yml run --rm django_kino_test python manage.py makemigrations --check --dry-run
          docker-compose -f test.yml run --rm django_kino_test mypy .
          docker-compose -f test.yml run django_kino_test pytest -n auto --create-db
      - name: Stop and remove containers
        run: |
          docker-compose -f test.yml down
          docker image rm postgres_kino_test
